/*
 * LibreSky Weather API
 *
 * An API for retrieving weather data.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::api_models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MeasurementHumidity {
    #[serde(rename = "variant")]
    pub variant: String,
    #[serde(rename = "sensor")]
    pub sensor: Box<api_models::Sensor>,
    #[serde(rename = "unit")]
    pub unit: api_models::GenericUnit,
    #[serde(rename = "value")]
    pub value: f64,
}

impl MeasurementHumidity {
    pub fn new(
        variant: String,
        sensor: api_models::Sensor,
        unit: api_models::GenericUnit,
        value: f64,
    ) -> MeasurementHumidity {
        MeasurementHumidity {
            variant,
            sensor: Box::new(sensor),
            unit,
            value,
        }
    }
}
