/*
 * LibreSky Weather API
 *
 * An API for retrieving weather data.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api_models;
use serde::{Deserialize, Serialize};

/// Report : Represents a series of Segments, reported at an instant in time.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Report {
    /// A Base64 string representing the station's public key
    #[serde(rename = "station_id")]
    pub station_id: String,
    #[serde(rename = "timestamp")]
    pub timestamp: i32,
    #[serde(rename = "segments")]
    pub segments: Vec<api_models::SegmentAtmospheric>,
    #[serde(rename = "coords", skip_serializing_if = "Option::is_none")]
    pub coords: Option<Box<api_models::GeoCoords>>,
}

impl Report {
    /// Represents a series of Segments, reported at an instant in time.
    pub fn new(station_id: String, timestamp: i32, segments: Vec<api_models::SegmentAtmospheric>) -> Report {
        Report {
            station_id,
            timestamp,
            segments,
            coords: None,
        }
    }
}

