/*
 * LibreSky Weather API
 *
 * An API for retrieving weather data.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api_models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SegmentAtmospheric {
    #[serde(rename = "variant")]
    pub variant: api_models::SegmentVariant,
    #[serde(rename = "temperature")]
    pub temperature: Box<api_models::MeasurementTemperature>,
    #[serde(rename = "pressure")]
    pub pressure: Box<api_models::MeasurementPressure>,
    #[serde(rename = "humidity")]
    pub humidity: Box<api_models::MeasurementHumidity>,
}

impl SegmentAtmospheric {
    pub fn new(variant: api_models::SegmentVariant, temperature: api_models::MeasurementTemperature, pressure: api_models::MeasurementPressure, humidity: api_models::MeasurementHumidity) -> SegmentAtmospheric {
        SegmentAtmospheric {
            variant,
            temperature: Box::new(temperature),
            pressure: Box::new(pressure),
            humidity: Box::new(humidity),
        }
    }
}

