/*
 * LibreSky Weather API
 *
 * An API for retrieving weather data.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api_models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Sensor {
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "datasheet_url", skip_serializing_if = "Option::is_none")]
    pub datasheet_url: Option<String>,
    #[serde(rename = "product_page", skip_serializing_if = "Option::is_none")]
    pub product_page: Option<String>,
}

impl Sensor {
    pub fn new(model: String) -> Sensor {
        Sensor {
            model,
            datasheet_url: None,
            product_page: None,
        }
    }
}

