/*
 * LibreSky Weather API
 *
 * An API for retrieving weather data.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::api_models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Endpoint {
    #[serde(rename = "variant")]
    pub variant: api_models::EndpointVariant,
    #[serde(rename = "supported")]
    pub supported: bool,
}

impl Endpoint {
    pub fn new(variant: api_models::EndpointVariant, supported: bool) -> Endpoint {
        Endpoint { variant, supported }
    }
}
