/*
 * LibreSky Weather API
 *
 * An API for retrieving weather data.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EndpointVariant {
    #[serde(rename = "stations")]
    Stations,
    #[serde(rename = "reports")]
    Reports,
    #[serde(rename = "forecasts")]
    Forecasts,
}

impl std::fmt::Display for EndpointVariant {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Stations => write!(f, "stations"),
            Self::Reports => write!(f, "reports"),
            Self::Forecasts => write!(f, "forecasts"),
        }
    }
}

impl Default for EndpointVariant {
    fn default() -> EndpointVariant {
        Self::Stations
    }
}
