/*
 * LibreSky Weather API
 *
 * An API for retrieving weather data.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api_models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GenericUnit {
    #[serde(rename = "percent")]
    Percent,
    #[serde(rename = "no_unit")]
    NoUnit,

}

impl std::fmt::Display for GenericUnit {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Percent => write!(f, "percent"),
            Self::NoUnit => write!(f, "no_unit"),
        }
    }
}

impl Default for GenericUnit {
    fn default() -> GenericUnit {
        Self::Percent
    }
}

