/*
 * LibreSky Weather API
 *
 * An API for retrieving weather data.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::api_models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MeasurementBase {
    #[serde(rename = "variant")]
    pub variant: String,
    #[serde(rename = "sensor")]
    pub sensor: Box<api_models::Sensor>,
}

impl MeasurementBase {
    pub fn new(variant: String, sensor: api_models::Sensor) -> MeasurementBase {
        MeasurementBase {
            variant,
            sensor: Box::new(sensor),
        }
    }
}
