/*
 * LibreSky Weather API
 *
 * An API for retrieving weather data.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PressureUnit {
    #[serde(rename = "kPa")]
    KPa,
    #[serde(rename = "hPa")]
    HPa,
    #[serde(rename = "Pa")]
    Pa,
    #[serde(rename = "mBar")]
    MBar,
    #[serde(rename = "bar")]
    Bar,
    #[serde(rename = "mmHg")]
    MmHg,
}

impl std::fmt::Display for PressureUnit {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::KPa => write!(f, "kPa"),
            Self::HPa => write!(f, "hPa"),
            Self::Pa => write!(f, "Pa"),
            Self::MBar => write!(f, "mBar"),
            Self::Bar => write!(f, "bar"),
            Self::MmHg => write!(f, "mmHg"),
        }
    }
}

impl Default for PressureUnit {
    fn default() -> PressureUnit {
        Self::KPa
    }
}
