/*
 * LibreSky Weather API
 *
 * An API for retrieving weather data.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api_models;
use serde::{Deserialize, Serialize};

/// SegmentBase : A segment is the data payload for a measurement. SegmentBase is the common fields shared between segments.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SegmentBase {
    #[serde(rename = "variant")]
    pub variant: api_models::SegmentVariant,
}

impl SegmentBase {
    /// A segment is the data payload for a measurement. SegmentBase is the common fields shared between segments.
    pub fn new(variant: api_models::SegmentVariant) -> SegmentBase {
        SegmentBase {
            variant,
        }
    }
}

