/*
 * LibreSky Weather API
 *
 * An API for retrieving weather data.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api_models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SegmentVariant {
    #[serde(rename = "std_atmospheric")]
    StdAtmospheric,

}

impl std::fmt::Display for SegmentVariant {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::StdAtmospheric => write!(f, "std_atmospheric"),
        }
    }
}

impl Default for SegmentVariant {
    fn default() -> SegmentVariant {
        Self::StdAtmospheric
    }
}

