/*
 * LibreSky Weather API
 *
 * An API for retrieving weather data.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::api_models::{self, ApiResult};
use axum::http::StatusCode;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerInfo {
    #[serde(rename = "status")]
    pub status: api_models::ServerStatus,
    #[serde(rename = "endpoints")]
    pub endpoints: Vec<api_models::Endpoint>,
}

impl ServerInfo {
    pub fn new() -> ServerInfo {
        ServerInfo {
            status: api_models::ServerStatus::Available,
            endpoints: vec![],
        }
    }
}
impl ApiResult for ServerInfo {
    fn content(self) -> impl Serialize {
        self
    }
    fn status_code(self) -> axum::http::StatusCode {
        StatusCode::OK
    }
}
