/*
 * LibreSky Weather API
 *
 * An API for retrieving weather data.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::api_models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Station {
    /// A Base64 string representing the station's public key
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "coords", skip_serializing_if = "Option::is_none")]
    pub coords: Option<Box<api_models::GeoCoords>>,
    #[serde(rename = "segments", skip_serializing_if = "Option::is_none")]
    pub segments: Option<Vec<api_models::SegmentVariant>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<api_models::StationStatus>,
    #[serde(rename = "first_heard", skip_serializing_if = "Option::is_none")]
    pub first_heard: Option<i32>,
    #[serde(rename = "last_heard", skip_serializing_if = "Option::is_none")]
    pub last_heard: Option<i32>,
}

impl Station {
    pub fn new() -> Station {
        Station {
            id: None,
            coords: None,
            segments: None,
            status: None,
            first_heard: None,
            last_heard: None,
        }
    }
}
