/*
 * LibreSky Weather API
 *
 * An API for retrieving weather data.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::api_models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StationsResponse {
    #[serde(rename = "prev", skip_serializing_if = "Option::is_none")]
    pub prev: Option<String>,
    #[serde(rename = "next", skip_serializing_if = "Option::is_none")]
    pub next: Option<String>,
    #[serde(rename = "data")]
    pub data: Vec<api_models::Station>,
}

impl StationsResponse {
    pub fn new(data: Vec<api_models::Station>) -> StationsResponse {
        StationsResponse {
            prev: None,
            next: None,
            data,
        }
    }
}

